// What "connect to a chain" means this session — the single seam deciding
// where chain bytes come from (design doc §3, "the read path"):
//
//   product-sdk container -> createChainClient: every connection is served
//                            by the HOST over the truapi port; the webview
//                            opens no sockets of its own.
//   plain browser (dev)   -> direct WebSockets to the gaming testnet
//                            (devClient.ts).
//   legacy embedded host  -> no connection at all: the chain layer stays
//                            inert (cached shelf / boot timeout only).
//
// All reads use the TYPED api over generated descriptors (.papi/,
// regenerated by `papi update` — wired into prebuild so a runtime
// upgrade surfaces as a typecheck failure, not a silently empty shelf).
// The same descriptors carry the genesis hashes the SDK uses to ask the
// host for each connection.
//
// People Chain is optional in every mode: a container that doesn't serve
// it degrades the shelf to owned-items-only (same rule as dev today) and
// is re-probed on every poll, so a host that gains the chain starts
// serving credits without an app restart.

import type { TypedApi } from 'polkadot-api'
import { createChainClient } from '@parity/product-sdk-chain-client'
import { ChainNotSupportedError } from '@parity/product-sdk-host'
import { gamingnetAssetHub, gamingnetPeople } from '@polkadot-api/descriptors'
import { isEmbedded, isInContainer } from '../host/embed'
import { devApis, destroyDevClients } from './devClient'
// Legacy-embedded hosts (no container) stay socket-free unless an
// explicit ?player= override asks for the QA sockets.
import { hasDevOverride } from './identity'

export type AssetHubApi = TypedApi<typeof gamingnetAssetHub>
export type PeopleApi = TypedApi<typeof gamingnetPeople>

/** The session's typed apis. `people` is null when that chain is
 *  unavailable (shelf degrades to owned-items-only). */
export interface ChainApis {
  assetHub: AssetHubApi
  people: PeopleApi | null
}

// ---- container path -------------------------------------------------------

interface ContainerSession {
  apis: ChainApis
  /** Probe the host for the People Chain when `apis.people` is null —
   *  called on every poll, so a host build that gains the chain is picked
   *  up without an app restart. No-op once connected. */
  refreshPeople: () => Promise<void>
  destroy: () => void
}

// One in-flight/settled session per generation; destroyClients() drops the
// reference and tears the client down via the promise, so a poll racing a
// teardown can never resurrect a destroyed client.
let containerSession: Promise<ContainerSession> | null = null

// The two chains are separate SDK clients on purpose: support is frozen
// into a client at creation (an unsupported chain is a proxy that throws
// forever), so re-probing the People Chain needs a fresh client — which
// must not tear down the healthy Asset Hub connection to get one.
async function openContainerSession(): Promise<ContainerSession> {
  const assetHubClient = await createChainClient({ chains: { assetHub: gamingnetAssetHub } })
  // Sockets are a dev affordance, NEVER a production fallback: a host
  // without Asset Hub fails the session, which the poll loop retries with
  // backoff (each retry re-asks the host, so a host build gaining the
  // chain is picked up) while the UI shows the connection-error state.
  // Only an explicit ?player=/?alias= QA override may fall back to the
  // dev sockets instead.
  try {
    void assetHubClient.assetHub.query
  } catch (err) {
    if (!(err instanceof ChainNotSupportedError)) throw err
    // Destroy the refused instance so the retry asks the host fresh.
    try { assetHubClient.destroy() } catch { /* unusable anyway */ }
    if (hasDevOverride()) {
      console.warn('[chain] host does not serve Asset Hub; QA override session using dev sockets')
      return { apis: devApis(), refreshPeople: async () => {}, destroy: () => {} }
    }
    console.warn('[chain] host does not serve Asset Hub; retrying')
    throw err
  }

  const apis: ChainApis = { assetHub: assetHubClient.assetHub, people: null }
  let destroyPeople: (() => void) | null = null
  let destroyed = false
  let warnedMissing = false
  let probing: Promise<void> | null = null

  async function probePeople(): Promise<void> {
    const client = await createChainClient({ chains: { people: gamingnetPeople } })
    try {
      void client.people.query
    } catch (err) {
      if (!(err instanceof ChainNotSupportedError)) throw err
      // Destroy the refused instance: it holds nothing, and dropping it
      // from the SDK's cache makes the next probe ask the host fresh
      // instead of replaying this answer.
      try { client.destroy() } catch { /* nothing held */ }
      if (!warnedMissing) {
        warnedMissing = true
        console.warn('[chain] host does not serve the People Chain; shelf is owned-items-only (re-probed each poll)')
      }
      return
    }
    if (destroyed) {
      try { client.destroy() } catch { /* already torn down */ }
      return
    }
    destroyPeople = () => client.destroy()
    apis.people = client.people
    if (warnedMissing) console.warn('[chain] the host now serves the People Chain; credits resume')
  }

  return {
    apis,
    refreshPeople: () => {
      if (apis.people || destroyed) return Promise.resolve()
      if (!probing) {
        probing = probePeople().finally(() => { probing = null })
      }
      return probing
    },
    destroy: () => {
      destroyed = true
      try { assetHubClient.destroy() } catch { /* already down */ }
      try { destroyPeople?.() } catch { /* already down */ }
    }
  }
}

// ---- the seam ---------------------------------------------------------------

/** The connections for this session, or null when there are none (legacy
 *  embedded host without the SDK — chain layer must stay inert, unless an
 *  explicit ?player= override asks for the QA sockets). */
export function getChainApis(): Promise<ChainApis | null> {
  if (isInContainer) {
    if (!containerSession) {
      const session = openContainerSession()
      containerSession = session
      // A failed handshake must not poison every later poll.
      session.catch(() => {
        if (containerSession === session) containerSession = null
      })
    }
    // Every poll gives the People Chain another chance (no-op once
    // connected); a hard probe failure surfaces as a poll error and takes
    // the normal rebuild path.
    return containerSession.then(async (s) => {
      await s.refreshPeople()
      return s.apis
    })
  }
  if (isEmbedded && !hasDevOverride()) return Promise.resolve(null)
  return Promise.resolve(devApis())
}

/** Tear down every connection so the next poll rebuilds them fresh
 *  (recovery from a wedged transport). Safe to call at any time. */
export function destroyClients(): void {
  const session = containerSession
  containerSession = null
  if (session) {
    session.then((s) => { try { s.destroy() } catch { /* already down */ } }, () => {})
  }
  destroyDevClients()
}
