// Lazy polkadot-api client singletons, one per chain, over whatever
// provider the session resolved (host seam or dev WebSocket).
//
// All reads use the TYPED api over generated descriptors (.papi/,
// regenerated by `papi update` — wired into prebuild so a runtime
// upgrade surfaces as a typecheck failure, not a silently empty shelf).

import { createClient, type TypedApi } from 'polkadot-api'
import { gamingnetAssetHub, gamingnetPeople } from '@polkadot-api/descriptors'
import { getChainProvider, type ChainId } from './connection'

export type AssetHubApi = TypedApi<typeof gamingnetAssetHub>
export type PeopleApi = TypedApi<typeof gamingnetPeople>

type Client = ReturnType<typeof createClient>

const clients = new Map<ChainId, Client>()

function clientFor(chain: ChainId): Client | null {
  let client = clients.get(chain)
  if (!client) {
    const provider = getChainProvider(chain)
    if (!provider) return null
    client = createClient(provider)
    clients.set(chain, client)
  }
  return client
}

/** Typed Asset Hub api, or null when the session has no provider for it. */
export function getAssetHubApi(): AssetHubApi | null {
  return clientFor('assetHub')?.getTypedApi(gamingnetAssetHub) ?? null
}

/** Typed People Chain api, or null when the session has no provider for it. */
export function getPeopleApi(): PeopleApi | null {
  return clientFor('people')?.getTypedApi(gamingnetPeople) ?? null
}

export function destroyClients(): void {
  for (const client of clients.values()) {
    try { client.destroy() } catch { /* already torn down */ }
  }
  clients.clear()
}
