// What "connect to a chain" means this session — the single seam deciding
// where chain bytes come from (design doc §3, "the read path"):
//
//   product-sdk container -> createChainClient: every connection is served
//                            by the HOST over the truapi port; the webview
//                            opens no sockets of its own.
//   plain browser (dev)   -> direct WebSockets to the gaming testnet.
//   legacy embedded host  -> no connection at all: the chain layer stays
//                            inert (cached shelf / boot timeout only).
//
// All reads use the TYPED api over generated descriptors (.papi/,
// regenerated by `papi update` — wired into prebuild so a runtime
// upgrade surfaces as a typecheck failure, not a silently empty shelf).
// The same descriptors carry the genesis hashes the SDK uses to ask the
// host for each connection.
//
// People Chain is optional in every mode: a container that doesn't serve
// it degrades the shelf to owned-items-only (same rule as dev today).

import { createClient, type TypedApi } from 'polkadot-api'
import { getWsProvider } from 'polkadot-api/ws'
import { createChainClient } from '@parity/product-sdk-chain-client'
import { ChainNotSupportedError } from '@parity/product-sdk-host'
import { gamingnetAssetHub, gamingnetPeople } from '@polkadot-api/descriptors'
import { isEmbedded, isInContainer } from '../host/embed'
// Legacy-embedded hosts (no container) stay socket-free unless an
// explicit ?player= override asks for the QA sockets.
import { hasDevOverride } from './identity'

export type AssetHubApi = TypedApi<typeof gamingnetAssetHub>
export type PeopleApi = TypedApi<typeof gamingnetPeople>

/** The session's typed apis. `people` is null when that chain is
 *  unavailable (shelf degrades to owned-items-only). */
export interface ChainApis {
  assetHub: AssetHubApi
  people: PeopleApi | null
}

/** Corey's gaming testnet endpoints. Dev fallback only — never used
 *  inside a host of any kind. */
export const TESTNET_WS = {
  assetHub: 'wss://gamingnet.substrate.dev/asset-hub', // spec: next-asset-hub-paseo
  people: 'wss://gamingnet.substrate.dev/people' // spec: Individuality Local
} as const

// ---- container path -------------------------------------------------------

interface ContainerSession {
  apis: ChainApis
  destroy: () => void
}

// One in-flight/settled session per generation; destroyClients() drops the
// reference and tears the client down via the promise, so a poll racing a
// teardown can never resurrect a destroyed client.
let containerSession: Promise<ContainerSession> | null = null

async function openContainerSession(): Promise<ContainerSession> {
  const client = await createChainClient({
    chains: { assetHub: gamingnetAssetHub, people: gamingnetPeople }
  })
  // A chain the host can't serve is a proxy that throws on first property
  // access. A host without Asset Hub falls back to the direct testnet
  // sockets — a TEMPORARY stand-in while no host build serves the
  // gamingnet chains; once hosts do, this fallback should narrow back to
  // ?player= QA sessions only. A missing People Chain just degrades the
  // shelf to owned-items-only.
  try {
    void client.assetHub.query
  } catch (err) {
    if (!(err instanceof ChainNotSupportedError)) throw err
    try { client.destroy() } catch { /* unusable anyway */ }
    console.warn('[chain] host does not serve Asset Hub; using direct testnet sockets')
    return { apis: devApis(), destroy: () => {} }
  }
  let people: PeopleApi | null = client.people
  try {
    void client.people.query
  } catch (err) {
    if (!(err instanceof ChainNotSupportedError)) throw err
    console.warn('[chain] host does not serve the People Chain; shelf is owned-items-only')
    people = null
  }
  return {
    apis: { assetHub: client.assetHub, people },
    destroy: () => client.destroy()
  }
}

// ---- dev path --------------------------------------------------------------

type DevClient = ReturnType<typeof createClient>
const devClients = new Map<keyof typeof TESTNET_WS, DevClient>()

function devClient(chain: keyof typeof TESTNET_WS): DevClient {
  let client = devClients.get(chain)
  if (!client) {
    client = createClient(getWsProvider(TESTNET_WS[chain]))
    devClients.set(chain, client)
  }
  return client
}

function devApis(): ChainApis {
  return {
    assetHub: devClient('assetHub').getTypedApi(gamingnetAssetHub),
    people: devClient('people').getTypedApi(gamingnetPeople)
  }
}

// ---- the seam ---------------------------------------------------------------

/** The connections for this session, or null when there are none (legacy
 *  embedded host without the SDK — chain layer must stay inert, unless an
 *  explicit ?player= override asks for the QA sockets). */
export function getChainApis(): Promise<ChainApis | null> {
  if (isInContainer) {
    if (!containerSession) {
      const session = openContainerSession()
      containerSession = session
      // A failed handshake must not poison every later poll.
      session.catch(() => {
        if (containerSession === session) containerSession = null
      })
    }
    return containerSession.then((s) => s.apis)
  }
  if (isEmbedded && !hasDevOverride()) return Promise.resolve(null)
  return Promise.resolve(devApis())
}

/** Tear down every connection so the next poll rebuilds them fresh
 *  (recovery from a wedged transport). Safe to call at any time. */
export function destroyClients(): void {
  const session = containerSession
  containerSession = null
  if (session) {
    session.then((s) => { try { s.destroy() } catch { /* already down */ } }, () => {})
  }
  for (const client of devClients.values()) {
    try { client.destroy() } catch { /* already torn down */ }
  }
  devClients.clear()
}
